import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

// Create reusable transporter object using SMTP transport
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.ethereal.email',
  port: parseInt(process.env.SMTP_PORT || '587', 10),
  secure: process.env.SMTP_PORT === '465', // true for 465, false for other ports
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

/**
 * Sends a password reset email to the given address.
 * 
 * @param to The recipient's email address
 * @param resetLink The full URL for resetting the password
 */
export async function sendPasswordResetEmail(to: string, resetLink: string): Promise<void> {
  const mailOptions = {
    from: process.env.EMAIL_FROM || '"PayDocs Support" <support@paydocs.local>',
    to,
    subject: 'Password Reset Request',
    text: `You requested a password reset. Please use the following link to reset your password: ${resetLink}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 5px;">
        <h2 style="color: #333; text-align: center;">Password Reset</h2>
        <p style="color: #555; line-height: 1.5;">Hello,</p>
        <p style="color: #555; line-height: 1.5;">You recently requested to reset your password for your account. Click the button below to proceed:</p>
        <div style="text-align: center; margin: 30px 0;">
          <a href="${resetLink}" style="background-color: #007bff; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px; font-weight: bold;">Reset Password</a>
        </div>
        <p style="color: #555; line-height: 1.5;">If you did not request a password reset, please ignore this email or contact support if you have concerns.</p>
        <p style="color: #777; font-size: 12px; margin-top: 40px; text-align: center;">This link will expire in 1 hour.</p>
      </div>
    `,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log(`Email sent: ${info.messageId}`);

    // In test environment, if using Ethereal, you can log the preview URL
    if (process.env.SMTP_HOST === 'smtp.ethereal.email' && nodemailer.getTestMessageUrl(info)) {
      console.log(`Preview URL: ${nodemailer.getTestMessageUrl(info)}`);
    }
  } catch (error) {
    console.error('Error sending password reset email:', error);
    throw new Error('Failed to send email');
  }
}

/**
 * Sends a generated payslip PDF to the employee.
 * 
 * @param to The employee's email address
 * @param pdfBuffer The generated PDF document buffer
 * @param employeeName The name of the employee
 * @param payPeriod The pay period string (e.g., "July 2026")
 */
export async function sendPayslipEmail(to: string, pdfBuffer: Buffer, employeeName: string, payPeriod: string): Promise<void> {
  const mailOptions = {
    from: process.env.EMAIL_FROM || '"PayDocs Support" <support@paydocs.local>',
    to,
    subject: `Your Payslip for ${payPeriod}`,
    text: `Hello ${employeeName},\n\nPlease find attached your payslip for the period of ${payPeriod}.\n\nBest regards,\nYour Company`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 5px;">
        <h2 style="color: #333; text-align: center;">Payslip: ${payPeriod}</h2>
        <p style="color: #555; line-height: 1.5;">Hello ${employeeName},</p>
        <p style="color: #555; line-height: 1.5;">Your payslip for <strong>${payPeriod}</strong> has been generated and is attached to this email.</p>
        <p style="color: #555; line-height: 1.5;">Please review the attached PDF document for your earnings and deductions details.</p>
        <p style="color: #777; font-size: 12px; margin-top: 40px; text-align: center;">This is an automated message generated by PayDocs.</p>
      </div>
    `,
    attachments: [
      {
        filename: `Payslip_${employeeName.replace(/\s+/g, '_')}_${payPeriod.replace(/\s+/g, '_')}.pdf`,
        content: pdfBuffer,
        contentType: 'application/pdf',
      },
    ],
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log(`Payslip email sent: ${info.messageId}`);

    if (process.env.SMTP_HOST === 'smtp.ethereal.email' && nodemailer.getTestMessageUrl(info)) {
      console.log(`Preview URL: ${nodemailer.getTestMessageUrl(info)}`);
    }
  } catch (error) {
    console.error('Error sending payslip email:', error);
    throw new Error('Failed to send payslip email');
  }
}

/**
 * Sends a generated invoice PDF to the client.
 * 
 * @param to The client's email address
 * @param pdfBuffer The generated PDF document buffer
 * @param clientName The name of the client
 * @param invoiceNumber The invoice number
 */
export async function sendInvoiceEmail(to: string, pdfBuffer: Buffer, clientName: string, invoiceNumber: string): Promise<void> {
  const mailOptions = {
    from: process.env.EMAIL_FROM || '"PayDocs Support" <support@paydocs.local>',
    to,
    subject: `Invoice ${invoiceNumber}`,
    text: `Hello ${clientName},\n\nPlease find attached your invoice (${invoiceNumber}).\n\nBest regards,\nYour Company`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 5px;">
        <h2 style="color: #333; text-align: center;">Invoice: ${invoiceNumber}</h2>
        <p style="color: #555; line-height: 1.5;">Hello ${clientName},</p>
        <p style="color: #555; line-height: 1.5;">Your invoice <strong>${invoiceNumber}</strong> has been generated and is attached to this email.</p>
        <p style="color: #555; line-height: 1.5;">Please review the attached PDF document for your billing details.</p>
        <p style="color: #777; font-size: 12px; margin-top: 40px; text-align: center;">This is an automated message generated by PayDocs.</p>
      </div>
    `,
    attachments: [
      {
        filename: `Invoice_${invoiceNumber.replace(/\s+/g, '_')}.pdf`,
        content: pdfBuffer,
        contentType: 'application/pdf',
      },
    ],
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log(`Invoice email sent: ${info.messageId}`);

    if (process.env.SMTP_HOST === 'smtp.ethereal.email' && nodemailer.getTestMessageUrl(info)) {
      console.log(`Preview URL: ${nodemailer.getTestMessageUrl(info)}`);
    }
  } catch (error) {
    console.error('Error sending invoice email:', error);
    throw new Error('Failed to send invoice email');
  }
}

/**
 * Sends a generated quotation PDF to the client.
 * 
 * @param to The client's email address
 * @param pdfBuffer The generated PDF document buffer
 * @param clientName The name of the client
 * @param quotationNumber The quotation number
 */
export async function sendQuotationEmail(to: string, pdfBuffer: Buffer, clientName: string, quotationNumber: string): Promise<void> {
  const mailOptions = {
    from: process.env.EMAIL_FROM || '"PayDocs Support" <support@paydocs.local>',
    to,
    subject: `Quotation ${quotationNumber}`,
    text: `Hello ${clientName},\n\nPlease find attached your quotation (${quotationNumber}).\n\nBest regards,\nYour Company`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 5px;">
        <h2 style="color: #333; text-align: center;">Quotation: ${quotationNumber}</h2>
        <p style="color: #555; line-height: 1.5;">Hello ${clientName},</p>
        <p style="color: #555; line-height: 1.5;">Your quotation <strong>${quotationNumber}</strong> has been generated and is attached to this email.</p>
        <p style="color: #555; line-height: 1.5;">Please review the attached PDF document for the details of our proposal.</p>
        <p style="color: #777; font-size: 12px; margin-top: 40px; text-align: center;">This is an automated message generated by PayDocs.</p>
      </div>
    `,
    attachments: [
      {
        filename: `Quotation_${quotationNumber.replace(/\s+/g, '_')}.pdf`,
        content: pdfBuffer,
        contentType: 'application/pdf',
      },
    ],
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log(`Quotation email sent: ${info.messageId}`);

    if (process.env.SMTP_HOST === 'smtp.ethereal.email' && nodemailer.getTestMessageUrl(info)) {
      console.log(`Preview URL: ${nodemailer.getTestMessageUrl(info)}`);
    }
  } catch (error) {
    console.error('Error sending quotation email:', error);
    throw new Error('Failed to send quotation email');
  }
}

/**
 * Sends a generated receipt PDF to the client.
 * 
 * @param to The client's email address
 * @param pdfBuffer The generated PDF document buffer
 * @param clientName The name of the client
 * @param receiptNumber The receipt number
 */
export async function sendReceiptEmail(to: string, pdfBuffer: Buffer, clientName: string, receiptNumber: string): Promise<void> {
  const mailOptions = {
    from: process.env.EMAIL_FROM || '"PayDocs Support" <support@paydocs.local>',
    to,
    subject: `Payment Receipt ${receiptNumber}`,
    text: `Hello ${clientName},\n\nPlease find attached your payment receipt (${receiptNumber}).\n\nThank you for your business,\nYour Company`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 5px;">
        <h2 style="color: #333; text-align: center;">Payment Receipt: ${receiptNumber}</h2>
        <p style="color: #555; line-height: 1.5;">Hello ${clientName},</p>
        <p style="color: #555; line-height: 1.5;">Your payment receipt <strong>${receiptNumber}</strong> has been generated and is attached to this email.</p>
        <p style="color: #555; line-height: 1.5;">Please review the attached PDF document for your payment details.</p>
        <p style="color: #777; font-size: 12px; margin-top: 40px; text-align: center;">This is an automated message generated by PayDocs.</p>
      </div>
    `,
    attachments: [
      {
        filename: `Receipt_${receiptNumber.replace(/\s+/g, '_')}.pdf`,
        content: pdfBuffer,
        contentType: 'application/pdf',
      },
    ],
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log(`Receipt email sent: ${info.messageId}`);

    if (process.env.SMTP_HOST === 'smtp.ethereal.email' && nodemailer.getTestMessageUrl(info)) {
      console.log(`Preview URL: ${nodemailer.getTestMessageUrl(info)}`);
    }
  } catch (error) {
    console.error('Error sending receipt email:', error);
    throw new Error('Failed to send receipt email');
  }
}

/**
 * Sends a secure 6-digit OTP verification email for new account registration.
 *
 * @param to The recipient's email address
 * @param otp The 6-digit one-time password
 */
export async function sendOtpEmail(to: string, otp: string): Promise<void> {
  const mailOptions = {
    from: process.env.EMAIL_FROM || '"PayDocs Security" <support@paydocs.local>',
    to,
    subject: `Your PayDocs Verification Code: ${otp}`,
    text: `Your PayDocs email verification code is: ${otp}. It will expire in 10 minutes. If you did not request this, please ignore this email.`,
    html: `
      <div style="font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif; max-width: 540px; margin: 0 auto; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.05);">
        <div style="background: linear-gradient(135deg, #3b82f6 0%, #6366f1 100%); padding: 32px 24px; text-align: center;">
          <div style="display: inline-block; width: 44px; height: 44px; background: rgba(255,255,255,0.2); border-radius: 12px; line-height: 44px; font-size: 22px; margin-bottom: 8px;">📄</div>
          <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 800; letter-spacing: -0.5px;">PayDocs</h1>
          <p style="color: rgba(255,255,255,0.9); margin: 6px 0 0; font-size: 13px; font-weight: 500;">Account Verification & Security</p>
        </div>
        <div style="padding: 36px 28px; background: #ffffff;">
          <h2 style="color: #0f172a; font-size: 20px; font-weight: 700; margin: 0 0 10px; letter-spacing: -0.3px;">Verify your email address</h2>
          <p style="color: #475569; font-size: 14px; line-height: 1.6; margin: 0 0 28px;">
            To ensure that your account is authentic and securely accessed only by you, please enter the following 6-digit verification code:
          </p>
          <div style="background: #f8fafc; border: 2px dashed #cbd5e1; border-radius: 12px; padding: 24px; text-align: center; margin-bottom: 28px;">
            <p style="color: #64748b; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 2px; margin: 0 0 10px;">Verification Code</p>
            <p style="color: #4f46e5; font-size: 38px; font-weight: 800; letter-spacing: 10px; margin: 0; font-family: 'Courier New', monospace;">${otp}</p>
          </div>
          <p style="color: #64748b; font-size: 12.5px; line-height: 1.6; margin: 0 0 8px;">
            ⏱ This code is valid for <strong>10 minutes</strong>. Never share this code with anyone.
          </p>
          <p style="color: #94a3b8; font-size: 12px; line-height: 1.5; margin: 0;">
            If you did not initiate this request, someone may have typed your email by accident. You can safely disregard this email.
          </p>
        </div>
        <div style="padding: 16px 28px; background: #f8fafc; text-align: center; border-top: 1px solid #f1f5f9;">
          <p style="color: #94a3b8; font-size: 11.5px; margin: 0;">© ${new Date().getFullYear()} PayDocs Accounting & Document Management. All rights reserved.</p>
        </div>
      </div>
    `,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log(`Verification OTP sent to ${to}: ${info.messageId}`);
    if (process.env.SMTP_HOST === 'smtp.ethereal.email' && nodemailer.getTestMessageUrl(info)) {
      console.log(`Preview URL: ${nodemailer.getTestMessageUrl(info)}`);
    }
  } catch (error) {
    console.error('Error sending OTP email:', error);
    throw new Error('Failed to send verification email');
  }
}

